const facts = ["you are loved more than you know.",
"let me guide you to a place where no one hurts you, you are safe here with me.",
"you have always wanted to caress every monster.",
"let me guide you to a place where no one hurts you.",
"still, a great deal of light falls on everything.",
"and the universe said i love you.",
"and the universe said you are not alone.",
"and the universe said you are the daylight.",
"and the universe said the light you seek is within you.",
"and the universe said i love you because you are love.",
"with every heartbeat i have left, i'll defend your every breath.",
"you'll be alright, no one can hurt you now.",
"i would love you in any form you take.",
"in the absense of everything, i promise to keep you warm.",
"if this fire goes out, i will keep you warm the best i can.",
"i will love you with every single thing i have.",
"i got dreams of my own, but i want to make yours come true.",
"to love means to radiate with inexhaustible light.",
"the universe and your spiritual guides are protecting you.",
"come to me, i’ll take care of you.",
"i’ll protect you, you know that i adore you.",
"all is full of love, all around you.",
"you'll be given love, you'll be taken care of.",
"you'll be given love, you have to trust it.",
"love is all / i dare to drown to be proven wrong.",
"you did your best, you did well.",
"the space in your voice shows the scale of your compassion.",
"hope is a muscle that allows us to connect.",
"everything you feel is good, if you would only let you.",
"i can't fix what was done to you, but i'll shield you from the rain.",
"if you need, come build your home in me.",
"always you have come trustingly to all that is terrible.",
"i'll be your lighthouse when you're lost at sea.",
"i'll keep my light on, baby you can always come to me.",
"in me, you will find a home.",
"you've still got me to hold you up, and i will never let you down.",
"if you can learn to love yourself, that love will continue to support you for the rest of your life.",
"what a privilege it is to love / a great honor to hold you up.",
"the world is brighter than the sun now that you're here.",
"you are loved more than you know / i hereby pledge all of my days to prove it so.",
"love everyone. every leaf. every ray of light. forgive.",
"i hope you know how proud i am you were created.",
"i love you, and i hope that you're okay.",
"and i will try to fix you.",
"i have left alone everything that i own / to make you feel like it's not too late, it's never too late.",
"the love you gave and have been given / weave into your own dream.",
"trust your head around / guide your stare elsewhere / you love is already waiting.",
"hold fort for love forever.",
"i will embody love for you.",
"maybe you were put on this earth to be tender and loving during a time when you are expected to be cruel and calloused."];

function newFact() {
  const randomFact = Math.floor(Math.random() * facts.length);
  document.getElementById('iloveyou').innerHTML = facts[randomFact];
}

// Call newFact() when the page loads
window.onload = newFact;